pull_request_rules:
  - name: v1.16 backport
    conditions:
      - label=v1.16
    actions:
      backport:
        assignees:
          - "{{ author }}"
          - "@fanatid"
        title: "{{ destination_branch }}: {{ title }} (backport of #{{ number }})"
        ignore_conflicts: true
        branches:
          - v1.16
